name: ESP32 Build with PlatformIO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PlatformIO
        uses: platformio/platformio-action@v1

      - name: Build ESP32 Project
        run: platformio run --target upload --environment esp32dev
