name: ESP32 Build with Arduino CLI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget

      - name: Install Arduino CLI
        run: |
          # Download the latest Arduino CLI release
          curl -fsSL https://github.com/arduino/arduino-cli/releases/download/0.30.0/arduino-cli_0.30.0_Linux_64bit.tar.gz -o arduino-cli.tar.gz
          
          # Extract and install Arduino CLI
          tar -xvzf arduino-cli.tar.gz
          sudo mv arduino-cli /usr/local/bin/
          
          # Verify installation
          arduino-cli version

      - name: Setup Arduino CLI and install ESP32 core
        run: |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32

      - name: Compile the ESP32 project
        run: |
          arduino-cli compile --fqbn esp32:esp32:esp32dev ESP32_WebPage.ino
