name: PlatformIO Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "esp32dev"
          targets: "upload"
          project-dir: "./"
          jobs: 4
          silent: false
          verbose: true
          disable-auto-clean: false
